### ISSUE TITLE
i have a problem when i install miband. how can i do?

### ISSUE THREAD

**Issue by DONGILBAE** [vshymanskyy/miband-js#17]
when i install miband rasberrypi.
i got this kind of error message.
how can i do?

node-pre-gyp ERR! Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.3.1/usb_bindings-v1.3.1-node-v48-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for usb@1.3.1 and node@6.13.1 (node-v48 ABI, glibc) (falling back to source compile with node-gyp)

**Comment by oleksbard** [comment]
This is an "issue" with `node-usb`. I suggest you to follow on https://github.com/tessel/node-usb/ or/and compile `node-usb` from source code since you are on linux.
