### ISSUE TITLE
HR is not working when using noble on linux (arm)

### ISSUE THREAD

**Issue by viktornord** [vshymanskyy/miband-js#19]
I am trying to use https://github.com/noble/noble for BLE communication & it works fine on MacOS. On RPi 3B+ running on Linux I can connect to the band & get some basic data from it but HR measurement is not working for some reason. Band does not want to start tracking (green lights are turned off). 
Do you know why this is happening?

**Comment by vshymanskyy** [comment]
@viktornord please be specific. What are the steps to reproduce? Also, consider posting an issue to noble, as it seems not related to MiBand.
