### ISSUE TITLE
Сreate a nice responsive UI for Web App

### ISSUE THREAD

**Issue by vshymanskyy** [vshymanskyy/miband-js#3]

**Comment by oleksbard** [comment]
Hey, I'll provide nicer UI today (simple reskin, no fancy stuff =) )

![2018-03-28_1129](https://user-images.githubusercontent.com/4028472/38017705-77ba4b36-327b-11e8-97eb-98818be81290.png)

PS: also I can't assign this issue to myself

**Comment by vshymanskyy** [comment]
@dnbard I hope you got it actually working with Chrome ;)

**Comment by vshymanskyy** [comment]
@dnbard Some development hints here: https://github.com/vshymanskyy/miband-js/blob/master/DEVELOPMENT.md

**Comment by oleksbard** [comment]
>  I hope you got it actually working with Chrome ;)

Unfortunately, no. Yet.
I've mocked everything for UI restyling =)

**Comment by vshymanskyy** [comment]
@dnbard thanks. Merged and deployed!

**Comment by oleksbard** [comment]
Let me know if you would have any UI-related ideas!
I'll try to find time to play with my MiBand)

**Comment by vshymanskyy** [comment]
@dnbard Just updated some colors and the demo picture on the main readme file. Thanks, this is MUCH better! ;)
