### ISSUE TITLE
Remove compiled JS files from repo

### ISSUE THREAD

**Issue by oleksbard** [vshymanskyy/miband-js#5]
What do you think about removing `public/webapp.bundle.js` and `public/webapp.bundle.js.map` from `master` branch ?

**Comment by vshymanskyy** [comment]
This is deployed to gh-pages atm, I think it's ok to leave it for now.
Also, public folder is listed in `.npmignore`. Would this be enough?

**Comment by oleksbard** [comment]
I just don't like an idea to push these files with every commit. Nevermind, it's priority of this issue is pretty low atm.

**Comment by vshymanskyy** [comment]
Done
